/*
Reexporting all those so client code does not have to install @aws-sdk/client-dynamodb just to check
for those errors. Those are missing the ThrottlingException and the ValidationException mentioned
in the documentations, but they aren't exported by the AWS package at the time of this writing.
*/
export {
  BackupInUseException,
  BackupNotFoundException,
  type BatchStatementError,
  BatchStatementErrorCodeEnum,
  ConditionalCheckFailedException,
  ContinuousBackupsUnavailableException,
  DuplicateItemException,
  ExportConflictException,
  ExportNotFoundException,
  type FailureException,
  GlobalTableAlreadyExistsException,
  GlobalTableNotFoundException,
  IdempotentParameterMismatchException,
  ImportConflictException,
  ImportNotFoundException,
  IndexNotFoundException,
  InternalServerError,
  InvalidEndpointException,
  InvalidExportTimeException,
  InvalidRestoreTimeException,
  ItemCollectionSizeLimitExceededException,
  LimitExceededException,
  PointInTimeRecoveryUnavailableException,
  PolicyNotFoundException,
  ProvisionedThroughputExceededException,
  ReplicaAlreadyExistsException,
  ReplicaNotFoundException,
  ReplicatedWriteConflictException,
  RequestLimitExceeded,
  ResourceInUseException,
  ResourceNotFoundException,
  TableAlreadyExistsException,
  TableInUseException,
  TableNotFoundException,
  TransactionCanceledException,
  TransactionConflictException,
  TransactionInProgressException,
} from "@aws-sdk/client-dynamodb";
